AZURE_REGIONS = [
    "brazilsouth",
    "canadaeast",
    "westeurope",
    "japanwest",
    "japaneast",
    "westcentralus",
    "westus2",
    "koreacentral",
    "koreasouth",
    "francecentral",
    "francesouth",
    "australiacentral",
    "uksouth",
    "ukwest",
    "eastasia",
    "australiacentral2",
    "australiaeast",
    "australiasoutheast",
    "southindia",
    "centralindia",
    "westindia",
    "centralus",
    "eastus",
    "eastus2",
    "westus",
    "northcentralus",
    "southcentralus",
    "northeurope",
    "canadacentral",
    "southafricanorth",
    "southafricawest",
    "southeastasia",
]

# TODO: add an option to select one region or all of them
AZURE_REGIONS = ['eastus2']